yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
]

yatube/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)


from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logged_out.html',
        ),
        name='logout',
    ),
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html',
        ),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html',
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html',
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
        ),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html',
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html',
        ),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, max_length=30)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='текст поста',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        verbose_name='дата публикации',
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='привязанная группа:',
        help_text='Группа, к которой будет относиться пост',
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'пост'
        verbose_name_plural = 'посты'

    def __str__(self) -> str:
        return self.text[:15]

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        labels = {
            'text': ('Пост'),
            'group': ('группа:'),
        }
        help_texts = {
            'text': ('Тут пишите буквы'),
            'group': ('Выберите из доступных:'),
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        # укажем модель, с которой связана создаваемая форма
        model = User
        # укажем, какие поля должны быть видны в форме и в каком порядке
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from yatube.settings import NUMBER_OF_POSTS
from .forms import PostForm
from .models import Group, Post, User
from .paginator import paginator


def index(request):
    template = 'posts/index.html'
    title = 'Последние записи'
    posts = Post.objects.select_related('author', 'group').all()
    page_number = request.GET.get('page')
    page_obj = paginator(posts, NUMBER_OF_POSTS, page_number)
    context = {
        'posts': posts,
        'title': title,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    template = 'posts/group_list.html'
    title = 'Записи сообщества '
    posts = group.posts.select_related('author', 'group').all()
    page_number = request.GET.get('page')
    page_obj = paginator(posts, NUMBER_OF_POSTS, page_number)
    context = {
        'title': title,
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    title = 'Профайл пользователя'
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('author', 'group').all()
    page_number = request.GET.get('page')
    page_obj = paginator(posts, NUMBER_OF_POSTS, page_number)
    post_counter = posts.count()
    context = {
        'title': title,
        'author': author,
        'page_obj': page_obj,
        'post_counter': post_counter,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post': post,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None)
    is_edit = False
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()
        return redirect('posts:profile', request.user)
    context = {
        'form': form,
        'is_edit': is_edit,
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    redir_template = 'posts:post_detail'
    post = get_object_or_404(Post, pk=post_id)
    is_edit = True
    form = PostForm(request.POST or None, instance=post)
    if request.user.id != post.author.id:
        return redirect(redir_template, post_id)
    if form.is_valid():
        form.save()
        return redirect(redir_template, post_id)
    context = {
        'form': form,
        'post': post,
        'is_edit': is_edit,
    }
    return render(request, template, context)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base_dives.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block cardheader %}
  <h1>Привет, я автор</h1>
{% endblock %}
{% block cardbody %}
  <p>
    Насяльнике! Ты тут картинкаманама ложиль, букве писаламанама!<br> Жамшут делать лучше хотель, но тут кошкаманама
    эшельбе-бешельме шайтанама!<br> Мы ей бархок дала казым хеир хотели а она шпыльтерей уууу шайтанама 
    и вот нет картинкаманама!<br> Не ругаисся насяльнике. Жамшут шпаклевкамана купиль. 
    Завтра все исправить, будит лущще еще. <br>
    Равшан
  </p>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
  <div class="row">
    <h1>Вот что я умею</h1>
    <aside class="col-6 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Python
        </li>
        <li class="list-group-item">
          Django
        </li>
      </ul>
    </aside>
  </div>
{% endblock %}

yatube/templates/base.html
<html lang="ru">
  {% load static %}
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link 
      rel="apple-touch-icon" 
      sizes="180x180" 
      href="img/fav/apple-touch-icon.png"
    >
    <link 
      rel="icon" 
      type="image/png" 
      sizes="32x32" 
      href="img/fav/favicon-32x32.png"
    >
    <link 
      rel="icon" 
      type="image/png" 
      sizes="16x16" 
      href="img/fav/favicon-16x16.png"
    >
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}>
    <title>{% block title %}Имя вкладки{% endblock %}</title>
  </head>
  <body>
    <header>
      {% include "includes/header.html" %}
    </header>
    <main>       
      {% block content %} 
        Контент вставлять сюда
      {% endblock %} 
    </main>
      {% include "includes/footer.html" %}   
  </body>
</html>

yatube/templates/base4password.html
<body>
    <title>{% block title %}имя вкладки{% endblock %}</title>
      <header>
        {% include "includes/header.html" %}
      </header>
      <main>
        <div class="container py-5"> 
            <div class="row justify-content-center">
              <div class="col-md-8 p-5">
                <div class="card">
                  <div class="card-header">
                    {% block contentheader %} 
                    Что в голове
                    {% endblock %} 
                  </div>
                  <div class="card-body"> 
                    {% block contentbody %} 
                    Что в теле
                    {% endblock %}
                  </div> <!-- card body -->
                </div> <!-- card -->
              </div> <!-- col -->
            </div> <!-- row -->
          </div> 
      </main>        
      <footer class="border-top text-center py-3">
        {% include "includes/footer.html" %}   
      </footer>
    </body>
  </html>

yatube/templates/base_dives.html
{% extends "base.html" %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% block cardheader %} 
              card-header вставлять сюда
            {% endblock %}
          </div>
          <div class="card-body">
            {% block cardbody %} 
              card-body вставлять сюда
            {% endblock %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/includes/error.html
{% load user_filters %}
{% if form.errors %}
  {% for field in form %} 
    {% for error in field.errors %}            
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>
    <a href="{% url 'about:author' %}">Об авторе</a>
    <a href="{% url 'about:tech' %}">Технологии</a>   
  </p>
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/form.html
{% load user_filters %}
{% for field in form %} 
  <div class="form-group row my-3">
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
    </label>
    {{ field|addclass:'form-control' }} 
    {% if field.help_text %}
      <small 
        id="{{ field.id_for_label }}-help"
        class="form-text text-muted"
      >
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
{% endfor %}

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href={% url 'posts:index' %}>
        <img src={% static 'img/logo.png' %} width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube</a>
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
              href="{% url 'about:author' %}"
              >
              Об авторе
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
              href="{% url 'about:tech' %}"
              >
              Технологии
            </a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item"> 
              <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
                href="{% url 'posts:post_create' %}"
                >
                Новая запись
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link {% if view_name  == 'users:password_change' %}active{% endif %}"
                href="{% url 'users:password_change' %}"
                >
                Изменить пароль
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link {% if view_name  == 'users:logout' %}active{% endif %}"
                href="{% url 'users:logout' %}"
                >
                Выйти
              </a>
            </li>
            <li>
              Пользователь: {{ user.username }}
            </li>
          {% else %}
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" 
                href="{% url 'users:login' %}"
                >
                Войти
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"  
                href="{% url 'users:signup' %}"
                >
                Регистрация
              </a>
            </li>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </nav>      
</header>

yatube/templates/includes/info_card.html
<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name}}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y"}}
    </li>
  </ul>      
  <p>
    {{ post.text }}
  </p>
</article>

yatube/templates/includes/pub_card.html
<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name}}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y"}}
    </li>
  </ul>      
  <p>
    {{ post.text }}
  </p>
  <a href="{% url 'posts:post_detail' post_id=post.pk %}">подробная информация </a><br>
  <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a><br>
  {% if request.user.id == post.author.id %}
    <a href="{% url 'posts:post_edit' post.id  %}">редактировать пост</a>
  {% endif %} 
</article> 

yatube/templates/posts/create_post.html
{% extends "base_dives.html" %} 
{% block title %}
  {% if is_edit %}
    Редактировать
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block cardheader %}
  {% include "includes/error.html" %}
  {% if is_edit %}
    Редактировать
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block cardbody %}      
  <form method="post">  
    {% csrf_token %}
    {% include "includes/form.html" %}
    <div class="d-flex justify-content-end">
      <button type="submit" class="btn btn-primary">
        {% if is_edit %}
          Сохранить
        {% else %}
          Добавить
        {% endif %}               
      </button>   
    </div>
  </form>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %} 
{% block title %}{{ title }}{{ group }}{% endblock %}
{% block content%}
  <div class="container py-5">
    <h1>{{ group }}</h1>
    <p>
      {{ group.description }}
    </p>
    {% for post in posts %}
      <article>
        {% include 'includes/pub_card.html'%}
        {% if not forloop.last %}<hr>{% endif %}
      </article>
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">
            Первая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Следующая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}    
    </ul>
  </nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
  <div class="container py-5">     
    <h1>{{ title }}</h1>
    {% for post in page_obj %}
      <article>
        {% include 'includes/pub_card.html'%}
        {% if post.group %}   
          <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
        {% endif %} 
        {% if not forloop.last %}<hr>{% endif %}
      </article>
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>  
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base_dives.html" %}
{% block title %}
  {{ post.text|truncatechars:30 }}
{% endblock %}
{% block cardheader %}
  <h2><p>Всего постов пользователя: <span>{{ post.author.post.count }}</span></p></h2>
  Текущий пост: <br>
{% endblock %}
{% block cardbody %}
  {{ post.text }}
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %} 
{% block title %}{{ title }} {{ author.get_full_name }}{% endblock %}
{% block content %}
  <div class="container py-5">   
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h2><p>Всего постов: {{ post_counter }}</p></h2>
    {% for post in page_obj %} 
      {% include "includes/pub_card.html" %}
      <hr>
    {% endfor %}
    {% include "posts/includes/paginator.html" %}
  </div> 
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Выход
        </div>
        <div class="card-body">
          <p>
            Вы вышли из своей учётной записи. Ждём вас снова!
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3"
                {% if field.field.required %} 
                  aria-required="true"
                {% else %}
                  aria-required="false"
                {% endif %}
              >
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                <div>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Войти
              </button>
              <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
                Забыли пароль?
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_change_done.html
<!DOCTYPE html> 
{% extends "base_dives.html" %}
{% block title %}Пароль изменён{% endblock %}
{% block cardheader %}Пароль изменён{% endblock %}
{% block cardbody %}<p>Пароль изменён успешно</p>{% endblock %}

yatube/templates/users/password_change_form.html
<!DOCTYPE html> 
{% extends "base_dives.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block cardheader %}Изменить пароль{% endblock %}
{% block cardbody %}
  <form method="post" action="../users/password_change_form.html">
    <input type="hidden" name="csrfmiddlewaretoken" value="">
    <div class="form-group row my-3 p-3">
      <label for="id_old_password">
        Старый пароль
        <span class="required text-danger">*</span>
      </label>    
      <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
    </div>
    <div class="form-group row my-3 p-3">
      <label for="id_new_password1">
        Новый пароль
        <span class="required text-danger">*</span>
      </label>    
      <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
      <small id="id_new_password1-help" class="form-text text-muted">
        <ul>
          <li>
            Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.
          </li>
          <li>
            Ваш пароль должен содержать как минимум 8 символов.
          </li>
          <li>
            Ваш пароль не может быть одним из широко распространённых паролей.
          </li>
          <li>
            Ваш пароль не может состоять только из цифр.
          </li>
        </ul>
      </small>
    </div>
    <div class="form-group row my-3 p-3">
      <label for="id_new_password2">
        Подтверждение нового пароля
        <span class="required text-danger">*</span>
      </label>    
      <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
    </div>
    <div class="col-md-6 offset-md-4">
      <button type="submit" class="btn btn-primary">
        Изменить пароль
      </button>
    </div>
  </form>
{% endblock %}

yatube/templates/users/password_reset_complete.html
<!DOCTYPE html> 
{% extends "base_dives.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block cardheader %}Восстановление пароля завершено{% endblock %}
{% block cardbody %}
  <p>Ваш пароль был сохранен. Используйте его для входа</p>
  <a href="../users/login.html">войти</a>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
<!DOCTYPE html> 
{% extends "base_dives.html" %}
{% block title %}Новый пароль{% endblock %}
{% load user_filters %}
{% if validlink %}
  {% block cardheader %}Введите новый пароль{% endblock %}
  {% block cardbody %}
    <form method="post" action="../users/lpassword_reset_confirm.html">
      <input type="hidden" name="csrfmiddlewaretoken" value="">
      <div class="form-group row my-3 p-3">
        <label for="id_new_password1">
          Новый пароль        
          <span class="required text-danger">*</span>        
        </label>    
        <input type="password" name="new_password1" class="form-control" required id="id_new_password1">      
        <small id="id_new_password1-help" class="form-text text-muted">
          <ul>
            <li>
              Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.
            </li>
            <li>
              Ваш пароль должен содержать как минимум 8 символов.
            </li>
            <li>
              Ваш пароль не может быть одним из широко распространённых паролей.
            </li>
            <li>
              Ваш пароль не может состоять только из цифр.
            </li>
          </ul>
        </small>      
      </div>
      <div class="form-group row my-3 p-3">
        <label for="id_new_password2">
          Подтверждение нового пароля        
          <span class="required text-danger">*</span>        
        </label>    
        <input type="password" name="new_password2" class="form-control" required id="id_new_password2">      
      </div>
      <div class="col-md-6 offset-md-4">
        <button type="submit" class="btn btn-primary">
          Назначить новый пароль
        </button>
      </div>
    </form>
  {% endblock %}
{% else %}
  {% block cardheader %}Ошибка{% endblock %}
  {% block cardbody %}
    <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
  {% endblock %}
{% endif %}

yatube/templates/users/password_reset_done.html
<!DOCTYPE html> 
{% extends "base_dives.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block cardheader %}Отправлено письмо{% endblock %}
{% block cardbody %}
  <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
{% endblock %}

yatube/templates/users/password_reset_form.html
<!DOCTYPE html> 
{% extends "base_dives.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block cardheader %}
  Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
{% endblock %}
{% block cardbody %}
  <form method="post" action="{% url 'users:password_reset_form' %}">
    <input type="hidden" name="csrfmiddlewaretoken" value="">
    <div class="form-group row my-3 p-3">
      <label for="id_email">
        Адрес электронной почты
        <span class="required text-danger">*</span>
      </label>    
      <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
    </div>
    <div class="col-md-6 offset-md-4">
      <button type="submit" class="btn btn-primary">
        Сбросить пароль
      </button>
    </div>
  </form>
{% endblock %}>

yatube/templates/users/signup.html
{% extends "base_dives.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block cardheader %}
    Зарегистрироваться
{% endblock %}
{% block cardbody %}
  {% include "includes/error.html" %}            
  <form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    {% include "includes/form.html" %}
    <div class="col-md-6 offset-md-4">
      <button type="submit" class="btn btn-primary">
        Зарегистрироваться
      </button>
    </div>
  </form>
{% endblock %}